### ISSUE TITLE
In tutorial section know is written twice

### ISSUE THREAD

**Issue by priyakumari02** [evildmp/diataxis-documentation-framework#125]
![image](https://github.com/evildmp/diataxis-documentation-framework/assets/77202746/361cba2b-b2d1-4bba-812c-b4cf839be4d8)

**Comment by priyakumari02** [comment]
In 8th line know is written twice

**Comment by agilgur5** [comment]
This is resolved by #143, #120, and #115

**Comment by iamDREAMO** [comment]
@agilgur5 I still see the repetition of "know" twice in the docs under the  same session.
Can I work on it?

**Comment by agilgur5** [comment]
> I still see the repetition of "know" twice in the docs under the same session

None of the existing PRs I linked have been merged as of yet.

> Can I work on it?

I'm not a maintainer (so you're asking the wrong person), but given that there are 3 existing PRs for it (with the oldest from ~1.5 years ago), I don't think there would be much point in that

**Comment by zmbc** [comment]
@evildmp would you be open to adding more maintainers on this project?
